apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/hello
images:
  - name: harbor.local/library/hello
    newTag: latest
patches:
  - target:
      kind: Deployment
      name: hello
    patch: |-
      - op: add
        path: /metadata/namespace
        value: apps
  - target:
      kind: Service
      name: hello
    patch: |-
      - op: add
        path: /metadata/namespace
        value: apps
  - target:
      kind: Gateway
      name: hello-gw
    patch: |-
      - op: add
        path: /metadata/namespace
        value: apps
  - target:
      kind: VirtualService
      name: hello-vs
    patch: |-
      - op: add
        path: /metadata/namespace
        value: apps
