apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cloudnative-pg-cluster
patches:
  - target:
      kind: Cluster
      name: postgres
    patch: |-
      - op: replace
        path: /spec/storage/storageClass
        value: local-path
