apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/baojiliu/myk8s.git
    targetRevision: HEAD
    path: platform/overlays/local/clickhouse-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
