apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.16.4
      helm:
        valueFiles:
          - $values/platform/base/harbor/values-local.yaml
    - repoURL: https://github.com/baojiliu/myk8s.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
